name: Docs to Pages
on:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install poetry
      run: |
        pip install "poetry>=1.8.2,<2"
    - name: Install docs building dependencies
      run: |
        poetry --version
        make install-docs
    - name: Build documentation
      run: |
        pushd doc
        poetry run make html
        touch build/html/.nojekyll
        popd
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: doc/build/html
        branch: gh-pages
