name: Docs to Pages
on:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.7.13'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
    - name: Install docs building dependencies
      run: |
        python3 -m pip install --upgrade pip
        make install-docs
    - name: Build documentation
      run: |
        pushd doc
        poetry run make html
        touch build/html/.nojekyll
        popd
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: doc/build/html
        branch: docs
